module.exports = {
    "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJjYWNoZSI6IlVzZXJfNTA3ZDc2MGE4NWYwNGJlYjk0YTZmOTkxZDBkODA1MWMiLCJ1aWQiOiJhcHIxU2hhaGlkRW5LdGtJdmgyS2thMzFnb3p6OWc3cjAiLCJkaWQiOiJXZWIiLCJzdWJpZCI6IjUwN2Q3NjBhODVmMDRiZWI5NGE2Zjk5MWQwZDgwNTFjIiwic3ViIjoic2hhaGlkLXRva2VuLWVuY29kZSIsImlzcyI6InNoYWhpZC10b2tlbi1lbmNvZGUiLCJpYXQiOjE1ODc0NjkyMzUsImV4cCI6MTYxOTAwNTIzNX0.UChmd5mF507OvtFgGl_G4jA3MOdkHfpYIExACQYndKE",
    "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJjYWNoZSI6IlVzZXJfNTA3ZDc2MGE4NWYwNGJlYjk0YTZmOTkxZDBkODA1MWMiLCJ1aWQiOiJhcHIxU2hhaGlkRW5LdGtJdmgyS2thMzFnb3p6OWc3cjAiLCJkaWQiOiJXZWIiLCJzdWJpZCI6IjUwN2Q3NjBhODVmMDRiZWI5NGE2Zjk5MWQwZDgwNTFjIiwic3ViIjoic2hhaGlkLXRva2VuLWVuY29kZSIsImlzcyI6InNoYWhpZC10b2tlbi1lbmNvZGUiLCJpYXQiOjE1ODc0NjkyMzUsImV4cCI6MTYxOTAwNTIzNX0.UChmd5mF507OvtFgGl_G4jA3MOdkHfpYIExACQYndKE",
    "menuItems": [
        "shows",
        "catalogs",
        "channels",
        "playlists"
    ]
}