module.exports = {
  "content": [
    {
      id: "5ecddf36cab959033b10a42e",
      name: "Block Checkout for 3 Hours",
      type: "Limit Temporary",
      paymentGateway: "Checkout",
      eventType: "Subscription Revoked",
      eventValue: "3",
      timeRangeDuration: 2,
      timeRangeDurationUnit: "Hours",
      action: "Block Payment",
      actionDuration: 1,
      actionDurationUnit: "Hour",
      status: "inactive",
    },
    {
      id: "11111",
      name: "Block Checkout for 1 Day",
      type: "Limit Temporary",
      paymentGateway: "Checkout",
      eventType: "Subscription Revoked",
      eventValue: "6",
      timeRangeDuration: 8,
      timeRangeDurationUnit: "Hours",
      action: "Block Payment",
      actionDuration: 1,
      actionDurationUnit: "Day",
      status: "inactive",
    },
    {
      id: "2222",
      name: "Blacklist Checkout",
      type: "Limit Temporary",
      paymentGateway: "Checkout",
      eventType: "Subscription Revoked",
      eventValue: "8",
      timeRangeDuration: 48,
      timeRangeDurationUnit: "Hours",
      action: "Blacklist",
      actionDuration: null,
      actionDurationUnit: null,
      status: "active",
    },
    {
      id: "3333",
      name: "Stop Retrial on Stolen",
      type: "Stop Retrial",
      paymentGateway: "Checkout",
      eventType: "Authorization",
      eventValue: "Decline Stolen",
      timeRangeDuration: null,
      timeRangeDurationUnit: null,
      action: "Stop Retrial",
      actionDuration: null,
      actionDurationUnit: null,
      status: "active",
    },
  ],
  numberOfElements: 25,
  totalElements: 88,
};
